### PR TITLE
Trying scikit build core

### PR DESCRIPTION
**Pull request by harrkee**

### CODE REVIEW

**Comment by mkrompiec** [comment]
Great to see the test on linux passes!

**Comment by mkrompiec** [comment]
related to https://github.com/ghdl/ghdl/issues/949 ?

**Comment by harrkee** [comment]
Okay, both runners now _install_ pyscf-ac0 correctly with some compiler massaging. But the test itself appears to fail for macos... @mkrompiec the answers appear to agree up to 6 decimal places. Is this something to be concerned about? Or can we soften the test tolerance?

**Comment by mkrompiec** [comment]
I suggest softening the test tolerance. 1 microhartree is acceptable numerical noise IMHO

**Comment by mkrompiec** [comment]
awesome

**Pull request merged**
